# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.DateTimeField(auto_now_add=True)),
                ('start_image', models.CharField(default='', max_length=254)),
                ('end_image', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=100)),
                ('from_password', models.CharField(max_length=100)),
                ('to_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inside_DHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(default=60)),
                ('Humidity', models.FloatField(default=40)),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxMinDHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.FloatField(default=60)),
                ('min_temp', models.FloatField(default=60)),
                ('max_humidity', models.FloatField(default=60)),
                ('min_humidity', models.FloatField(default=60)),
                ('day', models.BooleanField(default=True)),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outside_DHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(default=60)),
                ('Humidity', models.FloatField(default=40)),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
