# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbox', '0002_maxmindht_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorstate',
            name='inside',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doorstate',
            name='servo_pos',
            field=models.IntegerField(default=60),
        ),
    ]
