# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbox', '0003_auto_20171226_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doorstate',
            old_name='inside',
            new_name='door_open',
        ),
    ]
