# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbox', '0004_auto_20171226_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxmindht',
            name='now',
        ),
        migrations.AddField(
            model_name='maxmindht',
            name='max_humidity_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 2, 11, 22, 807592)),
        ),
        migrations.AddField(
            model_name='maxmindht',
            name='max_temp_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 2, 11, 22, 807023)),
        ),
        migrations.AddField(
            model_name='maxmindht',
            name='min_humidity_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 2, 11, 22, 807861)),
        ),
        migrations.AddField(
            model_name='maxmindht',
            name='min_temp_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 2, 11, 22, 807324)),
        ),
    ]
