# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbox', '0005_auto_20171227_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxmindht',
            name='max_humidity_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='maxmindht',
            name='max_temp_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='maxmindht',
            name='min_humidity_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='maxmindht',
            name='min_temp_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
