# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbox', '0006_auto_20171227_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.DateTimeField(auto_now_add=True)),
                ('ammonia', models.FloatField(default=0)),
                ('carbon_monoxide', models.FloatField(default=0)),
                ('nitrogen_dioxide', models.FloatField(default=0)),
                ('propane', models.FloatField(default=0)),
                ('iso_butane', models.FloatField(default=0)),
                ('methane', models.FloatField(default=0)),
                ('hydrogen', models.FloatField(default=0)),
                ('ethanol', models.FloatField(default=0)),
                ('R0_0', models.FloatField(default=0)),
                ('R0_1', models.FloatField(default=0)),
                ('R0_2', models.FloatField(default=0)),
                ('Rs_0', models.FloatField(default=0)),
                ('Rs_1', models.FloatField(default=0)),
                ('Rs_2', models.FloatField(default=0)),
            ],
        ),
    ]
